### ISSUE TITLE
Assertions

### ISSUE THREAD

**Issue by egroge** [flintlang/flint-2#10]
At the moment, flint 2 does not support assert statements

**Comment by SusanEisenbach** [comment]
Interesting - they are probably more important than strengthening the types (wash your mouth out Susan).

Susan

On 22 Jul 2020, at 14:47, George Stacey <notifications@github.com> wrote:

﻿

At the moment, flint 2 does not support assert statements

**Comment by mrRachar** [comment]
Note, that this doesn't require a verifier, as the original assertions (before Flint 1 introduced the verifier) are checked at runtime (as they can contain dynamic information) and revert the transaction. For Move this is particularly easy, as it provides its own `assert(..,n)` in the runtime.

**Comment by egroge** [comment]
I will implement this by adding a new assertion statement, and parsing assert as one of these rather than as a function. It will then generate the equivalent move assertion, with the number error message corresponding to the line in the flint file where the assertion is declared
