### ISSUE TITLE
Type states

### ISSUE THREAD

**Issue by mrRachar** [flintlang/flint-2#4]
Type states ensure that certain actions occur only when a contract is in the correct accepting state. This can ensure that only delivered goods can have their compensation withdrawn, or only pending contracts can be cancelled. This functionality is available with Flint, so should be implemented to get Flint 2 up to speed. The following description of caller protections comes from the language documentation.

### Type states

Flint introduces the concept of type states. Insufficient and incorrect state management in Solidity code have led to security vulnerabilities and unexpected behaviour in widely deployed smart contracts. Avoiding these vulnerabilities by the design of the language is a strong advantage.

Type states of a contract represent the possible states it can be in. At any point of time, the contract on the network can only exist in a single state. Special [`become` statements](#become-statements) can be used within functions to move the contract to a different type state.

A contract declaration may optionally include a list of its type states:

```swift
contract <name> (<type-state-1>, <type-state-2>, ...) {
  // constant and variable declarations, event declarations
}
```

Type states should be valid identifiers, starting with a capital letter.

Example:

```swift
contract Auction (Preparing, InProgress, Terminated) {}
```

Using [type state protection](#type-state-protection), it is possible to specify that only certain functions will be callable when the contract is in a given type state.

#### Type state protection

A protection block may also be used to ensure that certain functions are only called when the contract is in a given type state.

```swift
<contract-name> @(<type-state>) :: (<caller-group>) {
  // functions
}
```

Example:

```swift
contract Poll(Open, CountingVotes, Result) {
  // ...
}

Poll @(Open) :: (any) {
  public func voteFor(option: String) {
    // ...
  }
}
```

In this example the `voteFor` function could only be called when the `Poll` was in the `Open` state.

For more about protection blocks, see the language guide [section on them](https://github.com/flintlang/flint/blob/master/docs/language_guide.md#protection-blocks).

**Comment by egroge** [comment]
I am assuming the answer is yes, but can you have a function that can be used with many type states? 

Using the above example, we might want something like this:
`Poll @(Open, CountingVotes) :: (any) {
    public func screamAtTheOpposition() {}
}`

**Comment by mrRachar** [comment]
Definitely, as the parser already permits
